Web/Controllers/ResetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using System.Security.Cryptography;
namespace Web.Controllers
{
    public class ResetController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.email = true;
            return View();
        }
        private static Random random = new Random();
        private string GetCode(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
        public IActionResult Email(ResetModel model, string submit)
        {
            if (submit == "send")
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Index");
                }
            }
            ViewBag.email = false;
            CodeModel modelCodeTemp = new CodeModel();
            modelCodeTemp.code = GetCode(5);
            return View("Index", modelCodeTemp);
        }
        public IActionResult Verify(CodeModel model)
        {
            if (!TryValidateModel(model,nameof(model)))
            {
                ViewBag.email = false;
                model.confirmCode = "";
                return View("Index", model);
            }
            return View("Reseted");
        }
    }
}

Web/Views/Reset/Index.cshtml
<h2>Reset Your Password</h2>


@if (ViewBag.email)
{
    @Html.Partial("_EmailForm")
}
else
{
    @Html.Partial("_CheckForm")
}

Web/Views/Reset/_CodeForm.cshtml
@model Web.Models.CodeModel
<div>
    <form asp-antiforgery="true" asp-action="Verify" asp-controller="Reset">
        <div class="validation">
            <label asp-for="confirmCode"></label>
            <input type="text" asp-for="confirmCode" />
            <span asp-validation-for="confirmCode"></span>
        </div>
        <h3>@Model.code</h3>
        <input style="display:none" name="code" value="@Model.code" />
        <button type="submit" name="submit">Verify</button>
    </form>
</div>